const HEDERA_ETHRPC_PORT = process.env.HEDERA_ETHRPC_PORT || 58545;
const HEDERA_ETHRPC_PROVIDER = process.env.HEDERA_ETHRPC_PROVIDER || 'mainnet';
const HEDERA_ETHRPC_HEARTBEAT_MS = Number(process.env.HEDERA_ETHRPC_HEARTBEAT_MS) || 2000;
console.log('HEDERA_ETHRPC_PORT=%s', HEDERA_ETHRPC_PORT);
console.log('HEDERA_ETHRPC_PROVIDER=%s', HEDERA_ETHRPC_PROVIDER);
console.log('HEDERA_ETHRPC_HEARTBEAT_MS=%s', HEDERA_ETHRPC_HEARTBEAT_MS);

export default {HEDERA_ETHRPC_PORT, HEDERA_ETHRPC_PROVIDER, HEDERA_ETHRPC_HEARTBEAT_MS};
